server:
  port: 8081

spring:
  application:
    name: ct-claims-processing-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/healthcare

  thymeleaf:
    cache: false
